services:
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://leaderboard_owner:XKxWby7PDM5R@ep-fancy-mode-a2wxm1lh.eu-central-1.aws.neon.tech/leaderboard?sslmode=require
    # depends_on:
    #   - db
    # networks:
    #   - mynetwork
#   db:
#     image: postgres:latest
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: leaderboard
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: leaderboard
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - mynetwork

# volumes:
#   postgres_data:
#     driver: local

# networks:
#   mynetwork:
#     driver: bridge
